# Generated by Django 5.0.4 on 2024-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="is_revisit",
            field=models.BooleanField(default=False, verbose_name="재방문 여부"),
        ),
    ]
