# Generated by Django 5.0.4 on 2024-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0002_visitor_is_revisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="전화번호"
            ),
        ),
    ]
